site_name: User Documentation
docs_dir: '../../docs/de'
site_dir: '../../generated/de'

theme:
  name: 'code-siemens-code-docs-theme'
  include_search_page: false
  search_index_only: true
  language: de

plugins:
  - search

use_directory_urls: false

markdown_extensions:
  - admonition
  - meta
  - attr_list
  - footnotes
  - toc:
        permalink: true

nav:
  - zweck-der-dokumentation-git4:
      - zweck-der-dokumentation-git4: zweck-der-dokumentation-git4/zweck-der-dokumentation-git4.md
      - new-topic: zweck-der-dokumentation-git4/new-topic.md
  - gueltigkeitsbereich-der-dokumentation-git4:
      - gueltigkeitsbereich-der-dokumentation-git4: gueltigkeitsbereich-der-dokumentation-git4/gueltigkeitsbereich-der-dokumentation-git4.md
      - new-topic-2: gueltigkeitsbereich-der-dokumentation-git4/new-topic-2.md
  - new-topic: new-topic.md
